version: "3.5"
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/jcao/Documents/Development/Projects/Personal Projects/Portfolio/database/Postgres-DB/portfolio-db:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    container_name: redis
  backend:
    container_name: backend
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
  manager:
    container_name: manager
    build:
      context: ./manager
      dockerfile: Dockerfile.dev
    volumes:
      - ./manager:/app
      - /app/node_modules
    ports:
      - "4300:4300"
  nginx:
    depends_on:
      - backend
      - frontend
      - manager
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "4000:80"
