version: "3.5"
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:5432"
    volumes:
      - /home/jcao/Documents/Development/Projects/Personal Projects/Portfolio/database/Postgres-DB/portfolio-db:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    container_name: redis
  backend:
    container_name: backend
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=${NODE_ENV}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - AUTH_TYPE=${AUTH_TYPE}
      - EMAIL_ACCOUNT=${EMAIL_ACCOUNT}
      - EMAIL_CLIENT_ID=${EMAIL_CLIENT_ID}
      - EMAIL_CLIENT_SECRET=${EMAIL_CLIENT_SECRET}
      - EMAIL_REFRESH_TOKEN=${EMAIL_REFRESH_TOKEN}
      - EMAIL_ACCESS_TOKEN=${EMAIL_ACCESS_TOKEN}
    ports:
      - "3000:3000"
  
